apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-slave
  labels:
    app: redis
    role: slave
spec:
  replicas: 2
  selector:
    app: redis
    role: slave
  template:
    metadata:
      labels:
        app: redis
        role: slave
    spec:
      containers:
        - name: worker
          image: gcr.io/google_samples/gb-redisslave:v1
          env:
          - name: GET_HOSTS_FROM
            value: env 
          ports:
          - containerPort: 6379
